name: Build app

on:
  workflow_dispatch:
  pull_request:
    branches: ["main"]
  push:
    branches:
      - main
    paths-ignore:
      - ".github/**"

jobs:
  build-app:
    name: "Build ommer"
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup GraalVM
        uses: graalvm/setup-graalvm@v1
        with:
          java-version: '21'
          distribution: 'graalvm'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          native-image-job-reports: 'true'

      - name: Install native-image dependencies
        run: |
          sudo apt-get update
          sudo apt-get install build-essential libz-dev zlib1g-dev

      - name: Cache Gradle dependencies
        uses: actions/cache@v4
        id: cache-ommer
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/configuration-cache
          key: ${{ runner.os }}-${{ hashFiles('./build.gradle.kts', './settings.gradle.kts', './gradle.properties', '**/gradle-wrapper.properties') }}
          restore-keys: ${{ runner.os }}-gradle-

      - name: Build Kotlin app and create native image
        run: |
          chmod +x ./gradlew
          ./gradlew nativeCompile
          chmod +x ./ommer/build/native/nativeCompile/ommer

      - name: Set the date
        id: set_date
        run: |
          TAG_NAME=$(date +'%Y%m%d-%H%M%S')
          echo "TAG_NAME=${TAG_NAME}" >> $GITHUB_ENV

      - name: Prepare release artifact
        run: |
          cd ./ommer/build/native/nativeCompile/
          mv ommer ommer-linux-x86_64
          chmod +x ommer-linux-x86_64

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.TAG_NAME }}
          body: |
            New release of ommer native executable on ${{ env.TAG_NAME }}
            
            Platform: Linux x86_64
          files: |
            ./ommer/build/native/nativeCompile/ommer-linux-x86_64
