name: Build app

on:
  workflow_dispatch:
  pull_request:
    branches: ["main"]
  push:
    branches:
      - main  # Only trigger on build-app.yml changes
    paths-ignore:
      - ".github/workflows/generate-feed.yml"
      - "site/**"
      - "**/podcasts.json" 

jobs:
  build-app:
    name: "Build ommer"
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Cache Gradle dependencies
        uses: actions/cache@v4
        id: cache-ommer
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/configuration-cache
          key: ${{ runner.os }}-${{ hashFiles('./build.gradle.kts', './settings.gradle.kts', './gradle.properties', '**/gradle-wrapper.properties') }}
          restore-keys: ${{ runner.os }}

      - name: Build Kotlin app
        run: |
          java --version
          chmod +x ./gradlew
          ./gradlew build assemble

      - name: Set the date
        id: set_date
        run: |
          TAG_NAME=$(date +'%Y%m%d-%H%M%S')
          echo "TAG_NAME=${TAG_NAME}" >> $GITHUB_ENV

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.TAG_NAME }}
          body: "New release of ommer.jar on ${{ env.TAG_NAME }}"
          files: |
            ./ommer/build/libs/ommer.jar
