name: Build app

on:
  workflow_dispatch:
  pull_request:
    branches: ["main"]
  push:
    branches:
      - main
    paths-ignore:
      - "site/**"
      - "**/podcasts.json" 

jobs:
  build-app:
    name: "Build ommer"
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get version
        id: get_version
        run: |
          # Extract base version from build.gradle.kts
          BASE_VERSION=$(grep "^version = " build.gradle.kts | cut -d'"' -f2)
          # Split version into array
          IFS='.' read -ra PARTS <<< "$BASE_VERSION"
          COMMIT_HASH=$(git rev-parse --short HEAD)
          IS_PRERELEASE=false
          
          # Set next version (patch by default)
          NEXT_VERSION="${PARTS[0]}.${PARTS[1]}.$((PARTS[2] + 1))"
          
          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
            PR_BODY="${{ github.event.pull_request.body }}"
            PR_NUMBER="${{ github.event.pull_request.number }}"
            
            # Override next version based on PR template
            if [[ $PR_BODY == *"[x] major"* ]]; then
              NEXT_VERSION="$((PARTS[0] + 1)).0.0"
            elif [[ $PR_BODY == *"[x] minor"* ]]; then
              NEXT_VERSION="${PARTS[0]}.$((PARTS[1] + 1)).0"
            fi
            
            # For PR builds, use special version format
            VERSION="$BASE_VERSION-PR${PR_NUMBER}-${COMMIT_HASH}"
            IS_PRERELEASE=true
            
            # Extract description section from PR body
            DESCRIPTION=$(echo "$PR_BODY" | sed -n '/## Description/,/##/p' | sed '1d;$d')
            
          elif [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            # On main branch, use the determined next version
            VERSION="$NEXT_VERSION"
            
          else
            # For other branches, use branch name in version
            BRANCH_NAME=$(echo "${{ github.ref }}" | sed 's/refs\/heads\///')
            VERSION="$BASE_VERSION-${BRANCH_NAME}-${COMMIT_HASH}"
            IS_PRERELEASE=true
          fi
          
          # Update version in build.gradle.kts if on main
          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            sed -i "s/^version = .*/version = \"$VERSION\"/" build.gradle.kts
            git config --global user.name "GitHub Actions"
            git config --global user.email "actions@github.com"
            git add build.gradle.kts
            git commit -m "Bump version to $VERSION [skip ci]" || true
            git push || true
          fi
          
          # Set outputs
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "is_prerelease=$IS_PRERELEASE" >> $GITHUB_OUTPUT
          if [[ -n "$DESCRIPTION" ]]; then
            echo "description<<EOF" >> $GITHUB_OUTPUT
            echo "$DESCRIPTION" >> $GITHUB_OUTPUT
            echo "EOF" >> $GITHUB_OUTPUT
          fi

      - uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/configuration-cache
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      
      - name: Build Kotlin app
        env:
          JAVA_HOME: ${{ env.JAVA_HOME_21_X64 }}
        run: |
          echo "Using Java from: $JAVA_HOME"
          java --version
          chmod +x ./gradlew
          ./gradlew build assemble

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ steps.get_version.outputs.version }}
          prerelease: ${{ steps.get_version.outputs.is_prerelease }}
          body: |            
            Changes in this release:
            ${{ steps.get_version.outputs.description }}
          files: |
            ./ommer/build/libs/ommer.jar
