name: Build app

on:
  workflow_dispatch:
  pull_request:
    branches: ["main"]
  push:
    branches:
      - main
    paths-ignore:
      - ".github/**"

jobs:
  build-app:
    name: "Build ommer"
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "adopt"

      - name: Cache Gradle dependencies
        uses: burrunan/gradle-cache-action@v2
        with:
          arguments: build assemble

      - name: Set the date
        if: github.ref == 'refs/heads/main'
        id: set_date
        run: |
          TAG_NAME=$(date +'%Y%m%d-%H%M%S')
          echo "TAG_NAME=${TAG_NAME}" >> $GITHUB_ENV

      - name: Create Release
        uses: softprops/action-gh-release@v2
        if: github.ref == 'refs/heads/main'
        with:
          tag_name: ${{ env.TAG_NAME }}
          body: "New release of ommer.jar on ${{ env.TAG_NAME }}"
          files: |
            ./ommer/build/libs/ommer.jar
