name: Build app

on:
  workflow_dispatch:
  pull_request:
    branches: ["main"]
  push:
    branches:
      - main
    paths-ignore:
      - "site/**"
      - "**/podcasts.json"

jobs:
  build-app:
    name: "Build DrPodcast"
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get Version
        id: get_version
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          # Get latest release version from GitHub
          LATEST_VERSION=$(gh release list --limit 1 --repo ${{ github.repository }} --json tagName --jq '.[0].tagName' | sed 's/^v//')
          echo "Latest release version: $LATEST_VERSION"

          IFS='.' read -r major minor patch <<< "$LATEST_VERSION"

          if [ "${{ github.event_name }}" == "pull_request" ]; then
            PR_NUMBER="${{ github.event.pull_request.number }}"
            PR_DATA=$(gh api /repos/${{ github.repository }}/pulls/$PR_NUMBER --jq '{body: .body, title: .title}')
            PR_DESCRIPTION=$(echo "$PR_DATA" | jq -r .body)
            PR_TITLE=$(echo "$PR_DATA" | jq -r .title)

            if [[ $PR_DESCRIPTION == *"- [x] major"* ]]; then
              NEW_VERSION="$((major + 1)).0.0"
              echo "type=major" >> $GITHUB_OUTPUT
            elif [[ $PR_DESCRIPTION == *"- [x] minor"* ]]; then
              NEW_VERSION="${major}.$((minor + 1)).0"
              echo "type=minor" >> $GITHUB_OUTPUT
            else
              NEW_VERSION="${major}.${minor}.$((patch + 1))"
              echo "type=patch" >> $GITHUB_OUTPUT
            fi

            # Clean up PR description for release notes
            RELEASE_NOTES=$(echo "$PR_DESCRIPTION" | sed -n '/^## Description/,/^## Version Bump/p' | sed '/^## /d' | sed '/^$/d' | sed '/^- \[ \]/d')
            echo "description<<EOF" >> $GITHUB_OUTPUT
            echo "$PR_TITLE" >> $GITHUB_OUTPUT
            echo "" >> $GITHUB_OUTPUT
            echo "$RELEASE_NOTES" >> $GITHUB_OUTPUT
            echo "EOF" >> $GITHUB_OUTPUT
          else
            # On merge/push, get the PR type from commit message
            PR_TITLE=$(git log -1 --pretty=%B)
            if [[ $PR_TITLE == *"[major]"* ]]; then
              NEW_VERSION="$((major + 1)).0.0"
            elif [[ $PR_TITLE == *"[minor]"* ]]; then
              NEW_VERSION="${major}.$((minor + 1)).0"
            else
              NEW_VERSION="${major}.${minor}.$((patch + 1))"
            fi

            echo "description<<EOF" >> $GITHUB_OUTPUT
            echo "$PR_TITLE" >> $GITHUB_OUTPUT
            echo "EOF" >> $GITHUB_OUTPUT

            # Actually update version in csproj file
            sed -i "s|<Version>.*</Version>|<Version>$NEW_VERSION</Version>|" DrPodcast.csproj
          fi

          echo "version=$NEW_VERSION" >> $GITHUB_OUTPUT

      - name: Restore dependencies
        run: dotnet restore DrPodcast.sln

      - name: Build & Publish app
        run: dotnet publish -c Release -r linux-x64 --self-contained true -p:PublishSingleFile=true -o ./publish/

      - name: Copy podcasts.json to publish folder
        run: cp podcasts.json ./publish/

      - name: Commit version bump
        if: github.event_name == 'push'
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add DrPodcast.csproj
          git commit -m "Bump version to ${{ steps.get_version.outputs.version }}"
          git push

      - name: Create Release
        if: github.event_name == 'push'
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ steps.get_version.outputs.version }}
          body: ${{ steps.get_version.outputs.description }}
          files: |
            publish/**
