name: Build app

on:
  workflow_dispatch:
  pull_request:
    branches: ["main"]
  push:
    branches:
      - main
    paths-ignore:
      - "site/**"
      - "**/podcasts.json"

jobs:
  build-app:
    name: "Build ommer"
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get Version
        id: get_version
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          CURRENT_VERSION=$(grep "version = \".*\"" build.gradle.kts | cut -d'"' -f2)
          echo "Current version: $CURRENT_VERSION"
          
          IFS='.' read -r major minor patch <<< "$CURRENT_VERSION"
          
          if [ "${{ github.event_name }}" == "pull_request" ]; then
            PR_NUMBER="${{ github.event.pull_request.number }}"
            PR_DATA=$(gh api /repos/${{ github.repository }}/pulls/$PR_NUMBER --jq '{body: .body, title: .title}')
            PR_DESCRIPTION=$(echo "$PR_DATA" | jq -r .body)
            PR_TITLE=$(echo "$PR_DATA" | jq -r .title)
            
            if [[ $PR_DESCRIPTION == *"- [x] major"* ]]; then
              NEW_VERSION="$((major + 1)).0.0"
              echo "type=major" >> $GITHUB_OUTPUT
            elif [[ $PR_DESCRIPTION == *"- [x] minor"* ]]; then
              NEW_VERSION="${major}.$((minor + 1)).0"
              echo "type=minor" >> $GITHUB_OUTPUT
            else
              NEW_VERSION="${major}.${minor}.$((patch + 1))"
              echo "type=patch" >> $GITHUB_OUTPUT
            fi

            # Clean up PR description for release notes
            RELEASE_NOTES=$(echo "$PR_DESCRIPTION" | sed -n '/^## Description/,/^## Version Bump/p' | sed '/^## /d' | sed '/^$/d' | sed '/^- \[ \]/d')
            echo "description<<EOF" >> $GITHUB_OUTPUT
            echo "$PR_TITLE" >> $GITHUB_OUTPUT
            echo "" >> $GITHUB_OUTPUT
            echo "$RELEASE_NOTES" >> $GITHUB_OUTPUT
            echo "EOF" >> $GITHUB_OUTPUT
          else
            # On merge/push, get the PR type from commit message
            PR_TITLE=$(git log -1 --pretty=%B)
            if [[ $PR_TITLE == *"[major]"* ]]; then
              NEW_VERSION="$((major + 1)).0.0"
            elif [[ $PR_TITLE == *"[minor]"* ]]; then
              NEW_VERSION="${major}.$((minor + 1)).0"
            else
              NEW_VERSION="${major}.${minor}.$((patch + 1))"
            fi
            
            echo "description<<EOF" >> $GITHUB_OUTPUT
            echo "$PR_TITLE" >> $GITHUB_OUTPUT
            echo "EOF" >> $GITHUB_OUTPUT
            
            # Actually update version file on merge
            sed -i "s/version = \".*\"/version = \"$NEW_VERSION\"/" build.gradle.kts
          fi
          
          echo "version=$NEW_VERSION" >> $GITHUB_OUTPUT

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          
      - uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/configuration-cache
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Build app
        run: |
          java --version
          chmod +x ./gradlew
          ./gradlew build

      - name: Commit version bump
        if: github.event_name == 'push'
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add build.gradle.kts
          git commit -m "Bump version to ${{ steps.get_version.outputs.version }}"
          git push

      - name: Create Release
        if: github.event_name == 'push'
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ steps.get_version.outputs.version }}
          body: ${{ steps.get_version.outputs.description }}
          files: |
            ./ommer/build/libs/ommer.jar
