name: Execute Ommer and Update Feed

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  update-feed:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'adopt'
      
      - name: Execute ommer.jar
        run: java -jar ommer.jar
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          
      - name: Calculate MD5 of local feed.xml and base64 encode
        id: local_md5
        run: |
          MD5_HASH=$(md5sum output/genstart/feed.xml | awk '{print $1}' | xxd -r -p | base64)
          echo "LOCAL_MD5=$MD5_HASH" >> $GITHUB_ENV
          echo "LOCAL_MD5=$MD5_HASH"
      
      - name: Get contentMd5 of the blob in Azure Blob Storage
        id: blob_md5
        run: |
          BLOB_PROPERTIES=$(az storage blob show \
            --account-name ${{ secrets.STORAGE_ACCOUNT }} \
            --container-name ${{ secrets.CONTAINER_NAME }} \
            --auth-mode login \
            --name feed.xml \
            --query properties.contentSettings.contentMd5 -o tsv)
          echo "BLOB_MD5=$BLOB_PROPERTIES" >> $GITHUB_ENV
          echo "BLOB_MD5=$BLOB_PROPERTIES"
        env:
          AZURE_STORAGE_ACCOUNT: ${{ secrets.STORAGE_ACCOUNT }}
      
      - name: Upload feed.xml to Azure Blob Storage if different
        if: env.LOCAL_MD5 != env.BLOB_MD5
        run: |
          az storage blob upload \
            --account-name ${{ secrets.STORAGE_ACCOUNT }} \
            --container-name ${{ secrets.CONTAINER_NAME }} \
            --auth-mode login \
            --name feed.xml \
            --file output/genstart/feed.xml \
            --overwrite
        env:
          AZURE_STORAGE_ACCOUNT: ${{ secrets.STORAGE_ACCOUNT }}