name: Execute Ommer and Update Feed

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build-app:
    name: "Build Ommer"
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'adopt'
      
      - name: Build Kotlin app
        run: |
          chmod +x ./gradlew
          ./gradlew build assemble

      - name: Upload ommer.jar artifact
        uses: actions/upload-artifact@v3
        with:
          name: ommer-jar
          path: ./ommer/build/libs/ommer.jar

  update-feed:
    name: "Update ${{ matrix.podcast[0] }}"
    needs: build-app
    strategy:
      matrix:
        runs-on: [ubuntu-24.04]
        podcast: [
          ["genstart", "urn:dr:radio:series:5fa25ef8330eac2f135b62d6", "https://api.dr.dk/podcasts/v1/images/urn:dr:podcast:image:6593ba22846e9f8fc0338958.jpg"],
          ["sara-og-monopolet", "urn:dr:radio:series:5fa15704da351264f87b46ce", "https://api.dr.dk/podcasts/v1/images/urn:dr:podcast:image:6523bd03443243f95e2c39b0.jpg"],
          ["hjernekassen", "urn:dr:radio:series:5fa2684c330eac2f135b9254", "https://api.dr.dk/podcasts/v1/images/urn:dr:podcast:image:6523bd76443243f95e2c4866.jpg"]
        ]
    runs-on: ubuntu-24.04
    steps:
      - name: Download ommer.jar artifact
        uses: actions/download-artifact@v3
        with:
          name: ommer-jar
          path: ./

      - name: Execute ommer.jar
        run: java -jar ./ommer.jar ${{ matrix.podcast[0] }} ${{ matrix.podcast[1] }} ${{ matrix.podcast[2] }} ${{ secrets.API_KEY }}
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          
      - name: Calculate MD5 of local feed.xml and base64 encode
        id: local_md5
        run: |
          MD5_HASH=$(md5sum output/${{ matrix.podcast[0] }}.xml | awk '{print $1}' | xxd -r -p | base64)
          echo "LOCAL_MD5=$MD5_HASH" >> $GITHUB_ENV
          echo "LOCAL_MD5=$MD5_HASH"
      
      - name: Get contentMd5 of the blob in Azure Blob Storage
        id: blob_md5
        continue-on-error: true
        run: |
          BLOB_PROPERTIES=$(az storage blob show \
            --account-name ${{ secrets.STORAGE_ACCOUNT }} \
            --container-name ${{ secrets.CONTAINER_NAME }} \
            --auth-mode login \
            --name ${{ matrix.podcast[0] }}.xml \
            --query properties.contentSettings.contentMd5 -o tsv)
          echo "BLOB_MD5=$BLOB_PROPERTIES" >> $GITHUB_ENV
          echo "BLOB_MD5=$BLOB_PROPERTIES"
      
      - name: Upload feed.xml to Azure Blob Storage if different
        if: env.LOCAL_MD5 != env.BLOB_MD5
        run: |
          az storage blob upload \
            --account-name ${{ secrets.STORAGE_ACCOUNT }} \
            --container-name ${{ secrets.CONTAINER_NAME }} \
            --auth-mode login \
            --name ${{ matrix.podcast[0] }}.xml \
            --file output/${{ matrix.podcast[0] }}.xml \
            --overwrite
